# Generated by Django 4.2.7 on 2024-04-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_alter_admin_dashboard_total_faculties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_background', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('college_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='admin_dashboard',
            name='total_faculties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admin_dashboard',
            name='total_feedback',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admin_dashboard',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
